api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure: ~
    formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
    docs_formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
        jsonopenapi: ["application/vnd.openapi+json"]
        html: ["text/html"]
    # Good defaults for REST APIs
    defaults:
        pagination_client_items_per_page: true
        pagination_items_per_page: 10
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true

    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    mapping:
        paths:
            [
                "%kernel.project_dir%/src/Entity",
                "%kernel.project_dir%/src/Document",
            ]

    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
